### ISSUE TITLE
H5py version error

### ISSUE THREAD

**Issue by Arctic-Ambrun** [ManonDls/KFTS-InSAR#1]
Hi, I tried to use the test data, however, an bug occurred and Here is my result.
I suspect that caused by the different version of H5PY.

In my PC, the version of required wheels are:

h5py                      2.10.0           py36hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
matplotlib                3.3.4            py36h06a4308_0  
matplotlib-base           3.3.4            py36h62a2d02_0  
future                    0.18.2                   py36_1  
scipy                     1.5.2            py36h0b6359f_0  

Thank you!

![Screenshot from 2021-09-09 13-06-50](https://user-images.githubusercontent.com/81725312/132626158-d3f5d338-f8bd-400b-8fa4-d02a0ca592e8.png)

**Comment by ManonDls** [comment]
Hello, thank you for rising this issue. The problem was the systematic use of MPI... 
As the test does not require multiprocessing, I disabled the use of MPI in such configuration. 
To use multiprocessing, h5py has to be installed with the **openmpi and gcc8 dependency** so that there is no conflict in writing in the same file at the same time (I updated the requirement specifications in README.md)

**Comment by Arctic-Ambrun** [comment]
Thank you for your rapid response, really appreciate
Now seems the H5PY problem has been solved. 
Still there are some error in the name of the test data.
I suppose the name of test file has been renamed from States.h5 to Etna_sample.h5?
So the exist OS error.

![Screenshot from 2021-09-10 17-18-45](https://user-images.githubusercontent.com/81725312/132831435-ea288736-8265-4d59-8447-b98b45291f04.png)

**Comment by ManonDls** [comment]
Sorry the empty `KFTS` folder in testdata is missing, you can create it

**Comment by Arctic-Ambrun** [comment]
Thank you very much!
Still there are file missing, when processing the last command.
python plotoutput.py -c configs/config_Etna.ini  -geom ./ -rmsTh 2
It shows that there lack "RMS_map.h5" file in the /testdata/KFTS/RMS_map.h5

**Comment by ManonDls** [comment]
If the command `python kf2rms.py -c configs/config_Etna.ini` runs properly, it creates this file containing Root Mean Square errors.
