### ISSUE TITLE
ValueError while running 'checkinnov.py'

### ISSUE THREAD

**Issue by CanZhang-zc** [ManonDls/KFTS-InSAR#2]
Dear ManonDls,
Please, I meet a problem. 

I use the 'config_Etna_update.ini' to run KFTS. While running the command 'python checkinnov.py -c configs/config_Etna_update.ini', I got an error 'ValueError: x and y must have same first dimension, but have shapes (14,) and (60,)'. And there are no errors in other commands.

How should I solve it?
Sorry for any inconvenience caused, your assistance will be highly appreciated.

![issue](https://user-images.githubusercontent.com/78521332/142388718-ffcb9868-2386-44b0-b089-1d9b422e623a.jpg)

**Comment by ManonDls** [comment]
Dear CanZhang-zc, 

I identified two problems: 
- the default `configs/config_Etna_update.ini` places outputs at the same location as `configs/config_Etna.ini`. Creating a new folder would make things cleaner and allow the use of default configuration of `checkinnov.py`
- there was a mismatch between the number of analysis (i.e. number of new dates) and the number of phases adjusted (reanalysis + analysis). I updated the code to deal with this. 

Hope this will solve your problem

**Comment by CanZhang-zc** [comment]
Thanks a lot. I'm so sorry for not checking your reply in time.
I'll try using your solution. If there are any other questions, I'll ask again. 
Thank you so much!

**Comment by CanZhang-zc** [comment]
Dear ManonDls,
Thanks for your solution. I've solved the 'checkinnov.py' problem. And I have another problem I'd like to ask you.

If I want to use my own data (interferograms), how do I create .h5 file for KF through some specific steps (use 'createinput.py'?)?
If it's convenient for you, can you give some examples for me about how to create .h5 file?
By the way, before running 'kfts.py', are there any steps I need to take beforehand except create .h5 file and edit config file?

Sorry for any inconvenience caused, your assistance will be highly appreciated.

**Comment by ManonDls** [comment]
Dear CanZhang-zc,

KFTS works from **co-referenced unwrapped** interferograms. As an example you have `Etna_sample.h5` in testdata which includes a set of interferograms (20 by 20 pixels subset to limit storage on Github). To have information about the file content you can use `h5ls` in a terminal. It should output the name of datasets and their shapes:
```Jmat                     Dataset {214, 61}
bperp                    Dataset {214}
dates                    Dataset {61}
igram                    Dataset {214, 20, 20}
tims                     Dataset {61} 
``` 

where 214 is the number of interferograms and 61 the number of SAR acquisitions. So the first step is to convert your data into python arrays of adequate shape (similar structure than testdata) then to store them in a HDF5 file with h5py (https://docs.h5py.org/en/stable/high/dataset.html).
`createinput.py` is used to create synthetics data from scratch, but it may be useful (e.g. `writeh5input()`)

Hope it helps :-)

**Comment by CanZhang-zc** [comment]
Thanks a lot. I'll try using your solution. If there are any other questions, I'll ask again.
Thank you so much!

**Comment by CanZhang-zc** [comment]
Dear ManonDls,
I just use **vitables** open the **Etna_sample.h5**. It‘s visualized as shown below (see the figure).
It shows the name of datasets, including **dates, tims, bperp, Jmat, igram**.

According to your solution, I basically understand the meaning of the datasets, but there are a few things I don't understand:
What's the meaning of the number **20** and the dataset **Jmat**?
What's the unit of the dataset **dates**?
What's the meaning of each element in dataset **igram**?

Sorry for any inconvenience caused, your assistance will be highly appreciated.
![1](https://user-images.githubusercontent.com/78521332/147201683-443119c6-d969-44f0-a1bd-bc17d488be97.png)

**Comment by CanZhang-zc** [comment]
Dear ManonDls,
I have another question to ask.
What are the corresponding parameters of  **sig_a** in config?
Are the functional elements of descriptiv model (**model**)? But the number of parameters does not match. 

I tried to change **('POLY,1')** to **('POLY,2')**  in config to run testdata, and the terminal returns the **AssertionError: Too few uncertainties specified (4) in sig_a compare to model requirement (5)**.
So I don't know exactly what the relationship between **model** and **sig_a** is.

Sorry for any inconvenience caused, your assistance will be highly appreciated.

Here is where I have question in config:
**model  = [('POLY',1),('SIN',${freq}),('COS',${freq})]**
**sig_a  = 5.,1.,2.,2.**

**Comment by ManonDls** [comment]
Dear @CanZhang-zc, 
-- The number 20 is the number of pixels selected in the example subimage in Y and X. The full size data contains about a million pixels (`igram` of shape (214, 1165, 1000) for (number of interferograms, Y, X)) 
-- Jmat is the observation model matrix, that is the operator predicting interferograms from interferometric phases  
             _interferograms = Jmat phases_ 
-- dates are ordinal dates (https://pythontic.com/datetime/date/fromordinal) 
-- in the example, igram contains 214 interferograms 
-- as mentioned in the reference configuration file, sig_a is the _a priori standard deviation estimate of model parameters_. Basically, it defines the likely range of value for the expected model parameters. It is not a tight constraint but will greatly influence the parameter estimate of the first few assimilation steps. A large value of sig_a will give more freedom to adjust to the data but the uncertainty on output parameters will tend to be larger. As data grows, this parameter should have little impact. Please refer to the publication for more details [ **Dalaison and Jolivet (2020)** JGR; Figure 2.11 subplots A and D ]
-- If you increase the degree of the polynomial to two (a+ bx+ cx^2) then you have an additional parameter for which you need to define an _a priori_ distribution. sig_a contains the standard deviation for a distribution centred on zero.

**Comment by CanZhang-zc** [comment]
Sorry for not replying to your message for a long time.
I will read your help carefully, thank you so much.

**Comment by CanZhang-zc** [comment]
Dear @ManonDls ,
I have a new question to ask.

When I use my own .h5 files, the terminal reminds "Warning: post-fit residual too big (mean ＞10mm)".
I converted the **".diff“ files** of the interferograms into the dataset **igram** of.h5 files for processing.

I would like to ask you, what might be the problem with this warning?
Sorry for any inconvenience caused, your assistance will be highly appreciated.

**Comment by ManonDls** [comment]
Hello @CanZhang-zc 
This warning means the algorithm has difficulty reconciling the different interferograms, but KFTS still runs as usual. Often this arises when they are significant misclosure error in the data
