### ISSUE TITLE
OSError: Can't read data (no appropriate function for conversion path)

### ISSUE THREAD

**Issue by Bingquan-InSAR** [ManonDls/KFTS-InSAR#3]
Dear ManonDls,
Please, I meet a problem.

I use the 'config_Etna.ini' to run KFTS. While running the command ' python plotoutput.py -c configs/config_Etna.ini  -geom ./ -rmsTh 2', I got an error 'OSError: Can't read data (no appropriate function for conversion path)'. And there are no errors in other commands.

How should I solve it?
Sorry for any inconvenience caused, your assistance will be highly appreciated.
![1646487238(1)](https://user-images.githubusercontent.com/38463989/156885686-6f3304b8-f96d-4ca2-b230-f2de7c3af7a6.jpg)

**Comment by bjmarfito** [comment]
I have the same problem @libingquan13

**Comment by ManonDls** [comment]
Hello @libingquan13 and @bjmarfito,
This issue is now solved. Thank you for notifying me. 
It was due to an update of the h5py library and adding `dates = dates[:]` in `plotouput.py` did the trick.

**Comment by bjmarfito** [comment]
It works now. Thank you @ManonDls

**Comment by Bingquan-InSAR** [comment]
It works now. Thank you @ManonDls
