### ISSUE TITLE
Questions regarding input format

### ISSUE THREAD

**Issue by bjmarfito** [ManonDls/KFTS-InSAR#4]
Hi, is there a code in KFTS to generate h5 files from stack of unwrapped interferograms in ISCE2 or do I need to create my own code to generate an h5 file?

**Comment by CanZhang-zc** [comment]
> Hi, is there a code in KFTS to generate h5 files from stack of unwrapped interferograms in ISCE2 or do I need to create my own code to generate an h5 file?

Hello bjmarfito, Have you solved the problem?

**Comment by ManonDls** [comment]
Hello both, Thank you for your messages and interest. I will provide a code this week (I need to work a little on it) working for ISCE (version 1) and maybe ISCE2 equally.

**Comment by CanZhang-zc** [comment]
Thanks a lot, ManonDls.
And can this code be applied to both GAMMA/Mintpy? Or can it be modified to apply?

**Comment by bjmarfito** [comment]
Thank you @ManonDls!

**Comment by CanZhang-zc** [comment]
Thanks a lot, @ManonDls 
And can this code be applied to both GAMMA/Mintpy? Or can it be modified to apply?

**Comment by ManonDls** [comment]
Hello @CanZhang-zc  @bjmarfito, 
I uploaded a script that works with my setting. You can adjust the config file to fit to your needs (see README). I suspect that key functions in `prepare_input.py ` like `makefnames`  also has to be adjusted to your own file architecture. Please let me know if you encounter major problems.

**Comment by CanZhang-zc** [comment]
Thanks a lot, @ManonDls

**Comment by bjmarfito** [comment]
Thank you @ManonDls!
