### ISSUE TITLE
IndexError: Index (38) out of range for (0-19)

### ISSUE THREAD

**Issue by CanZhang-zc** [ManonDls/KFTS-InSAR#5]
Dear ManonDls,
Please, I meet a new problem. This problem occurred after I installed KFTS-InSAR with a new computer.

I use the 'config_Etna_update.ini' to run KFTS. While running 'python plotoutput.py -c configs/config_Etna.ini  -geom ./ -rmsTh 2' to take easy test, I got an error
 'IndexError: Index (38) out of range for (0-19)'. And there are no errors in other commands.

How should I solve it?
Sorry for any inconvenience caused, your assistance will be highly appreciated.
![image](https://user-images.githubusercontent.com/78521332/229096804-d454060f-110a-46e1-af24-f5f407c29054.png)

**Comment by ManonDls** [comment]
Thank you for rising this issue. I corrected this error
